### ISSUE TITLE
Data for thesis

### ISSUE THREAD

**Issue by gkapi** [eellak/gsoc2019-tms#1]
In models/thesis.js,  it is important to cover also the case where a thesis is assigned either by more than one professors or has more than one supervisor. Will this be resolved by just having both professor names for instance, in one string? In this case, maybe add a comment in the respective description.

**Comment by MichailChatzianastasis** [comment]
The case where a thesis has more than one supervisor is covered already because in assigned_thesis model i have an array where i store the supervisors. Also every thesis has one owner , so i think that is not possible for a thesis to be assigned by more than one professors.
